PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZJKT_METRIC_CUS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZJKT_METRIC_CUS-METRIC .
    FIELD ZJKT_METRIC_CUS-NAME .
    FIELD ZJKT_METRIC_CUS-MET_TYPE .
    FIELD ZJKT_METRIC_CUS-PROV_TYPE .
    FIELD ZJKT_METRIC_CUS-PROV_NAME .
    FIELD ZJKT_METRIC_CUS-DESCRIPTION .
    FIELD ZJKT_METRIC_CUS-ACTIVE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZJKT_METRIC_CUS-METRIC .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.