*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZJKT_MV_METRIC_CU01.
                    "TABLEFRAME_ZJKT_MV_METRIC_C
INCLUDE LZJKT_MV_METRIC_CU02.
                    "TABLEPROC_ZJKT_MV_METRIC_C